### ISSUE TITLE
Incompatible while installing on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by geo1004** [flexpaper/pdf2json#1]
Hi,

I'm trying to install pdf2json on an Ubuntu 14.04 x64 hosted on digital ocean but I get an incompatibility error '/usr/local/bin/pdf2json: cannot execute binary file: Exec format error' when running pdf2json.
Is this package x64 compatible?

Thanks
Geo

**Comment by flexpaper** [comment]
Yes it is, how did you compile and install it?

**Comment by geo1004** [comment]
I installed it on a Mac OS X system without any problem ( ./configure - make - sudo make install )

**Comment by flexpaper** [comment]
That's odd - we're running it on multiple Ubuntu x64 set ups including some on Linode, didn't get any warnings/errors when compiling it?

**Comment by geo1004** [comment]
I don't have any error. Here a pastebin with all the process: http://pastebin.com/XGeCQvFD

**Comment by flexpaper** [comment]
Sorry we really can't reproduce this, I just compiled it on one of our x64 servers on Linode and it executes fine. Can you check what the following command gives you?

uname -a

In our case it spits out
Linux (HOSTNAME) #1 SMP Mon Jun 22 10:39:23 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by flexpaper** [comment]
You could try to execute the following before you execute make but it really shouldn't make any difference as the application is x64 compatible. 

export CFLAGS='-m32'
export CXXFLAGS='-m32'
export LDFLAGS='-m32'

(and then execute ./configure && make)

**Comment by geo1004** [comment]
I've tried but no luck unfortunately.

**Comment by adlermedrado** [comment]
I tried and it compiled, but I got the following error:

```
adler@server:/tmp/swfs$ pdf2json 
-bash: /usr/local/bin/pdf2json: cannot execute binary file: Erro no formato exec
```

**Comment by flexpaper** [comment]
Do you know what processor type you have on the machine that is failing ?

**Comment by adlermedrado** [comment]
Sure, 

If you need more information, just ask.

```
adler@server:/$ cat /proc/cpuinfo | grep model | uniq
model		: 26
model name	: Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz
adler@server:/$ cat /proc/cpuinfo | grep vendor | uniq
vendor_id	: GenuineIntel
```

**Comment by flexpaper** [comment]
Is this a virtual machine? I just installed pdf2json yesterday on a 64 bits ubuntu within VMware fusion without problems, here are the details for this vm:

$ uname -a
Linux flexpaper-test 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo | grep model | uniq
model		: 58
model name	: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz

**Comment by bdecarne** [comment]
Same problem here !

```
bash: /usr/local/bin/pdf2json : fichier binaire impossible à lancer
```

$ uname -a
Linux hostname 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64 GNU/Linux

$ cat /proc/cpuinfo | grep model | uniq
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz

**Comment by flexpaper** [comment]
Still trying to reproduce this - It has to do with x64/ia32 compatibility but have not yet been able to get this error on a machine. I assume you ran 

./configure
make

before trying to execute src/pdf2json

?

**Comment by flexpaper** [comment]
To be able to reproduce this I installed a new Ubuntu 14.04 on Digital Ocean and installed pdf2json without problems. This is a clean Installation.

```
sudo apt-get update --fix-missing
sudo apt-get install build-essential
mkdir Code
cd Code
./configure
make
make install
```

```
$ uname -a
Linux flexpaper-test 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo | grep model | uniq
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
```

What are we doing differently?

**Comment by wanghaisheng** [comment]
$ uname -a
Linux edwin-clear 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo | grep model | uniq
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

git clone https://github.com/flexpaper/pdf2json.git
cd pdf2json
./configure --prefix=/opt/software/pdf2json
make 
make install

add export PATH="/opt/software/pdf2json:$PATH" to ~/.zshrc file
then 
$ pdf2json -v
zsh: 可执行文件格式错误: pdf2json

**Comment by stevenyeung** [comment]
Not sure if this is related, I am also building pdf2json on Ubuntu 14.04. When I built against the master branch, it fails like you guys stated above. But once I built against the [tagged][] version. It works fine.

[tagged]: https://github.com/flexpaper/pdf2json/releases/download/v0.68/pdf2json-0.68.tar.gz

Good luck!

**Comment by thisdarktao** [comment]
I'm experiencing the same issue on a Centos 7.x OVH VPS.

The usual ./configure, make, make install produced a binary in Mach-O format:

`/usr/local/bin/pdf2json: Mach-O 64-bit executable`

This clearly isn't correct!

**Comment by MrFahey** [comment]
Same issue compiling this on Centos 6.7 x64

as per @thisdarktao and @stevenyeung using the tagged version worked fine for me.

**Comment by jubayerarefin** [comment]
I am not sure if it is related. I am using on ubuntu 14.04-lts-x64

I was getting "cannot execute binary file: Exec format error" message after 1st install.

Then I did `./configure`, `make clean` and `sudo make install`

It is working now.
