### ISSUE TITLE
Reversing? JSON to PDF

### ISSUE THREAD

**Issue by floor66** [flexpaper/pdf2json#16]
Is it at all possible to reverse the objective of this program: to generate a PDF from the given JSON?

**Comment by flexpaper** [comment]
No, this library does not do reversing of JSON to PDF

**Comment by dezea** [comment]
> Is it at all possible to reverse the objective of this program: to generate a PDF from the given JSON?

Have you found a solution for this? I had a look at the json output and it can be done for sure with a little RE.

**Comment by floor66** [comment]
> > Is it at all possible to reverse the objective of this program: to generate a PDF from the given JSON?
> 
> Have you found a solution for this? I had a look at the json output and it can be done for sure with a little RE.

No, I haven't. Truth be told I forgot what I needed this for...
