### ISSUE TITLE
Split option names files incorrectly

### ISSUE THREAD

**Issue by twinj** [flexpaper/pdf2json#6]
If I use the -split option with 10 files are named - Paper.pdf_10.js, _20.js, _30.js...

However if i split with 1 or 5 (the two i tried) the count begins at 2 or 10 on the 2nd nth factor.

I am using windows 8 64bit

**Comment by futureweb** [comment]
I got the same Problem ... any fix for this?

**Comment by futureweb** [comment]
just tried it with latest version (updated ImgOutputDev.cc) - but this is not really working ... it's creating a filename-1.js File now - but that's empty ... and it still creates filename-maxPages+1.js ... if a PDF got 10 PAges - it creates 11 JS now with first one simply empty ...
It's always "actual page+1".js ...

**Comment by futureweb** [comment]
@flexpaper - I'm not 100% sure if this Change will work in every case ... but with split=1 it works for me ... feel free to merge the Pull request after you verified it works ... ;-)

https://github.com/flexpaper/pdf2json/pull/12

**Comment by flexpaper** [comment]
Did you supply the conversion tool with the "-split 10" parameter ?

**Comment by futureweb** [comment]
tested with 1 and 10 - booth working as far I can see

**Comment by futureweb** [comment]
@twinj - could you maybe confirm that it's working for you too? So @flexpaper can close the issue? ;-)

**Comment by flexpaper** [comment]
Fixed in 0.69
